# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overview.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1340, 768)
        self.centrawidget = QtWidgets.QWidget(MainWindow)
        self.centrawidget.setStyleSheet("background:none;\n"
"")
        self.centrawidget.setObjectName("centrawidget")
        self.overview = QtWidgets.QFrame(self.centrawidget)
        self.overview.setGeometry(QtCore.QRect(20, 230, 1312, 403))
        self.overview.setMaximumSize(QtCore.QSize(16777215, 8765))
        self.overview.setStyleSheet("QFrame#overview{background-color: rgba(0, 0, 0, 100); border-radius:15px;}")
        self.overview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.overview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.overview.setObjectName("overview")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.overview)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.timeplan = QtWidgets.QFrame(self.overview)
        self.timeplan.setMaximumSize(QtCore.QSize(16777215, 40))
        self.timeplan.setStyleSheet("background-color:rgb(0,0,0,80); border-radius:15px;")
        self.timeplan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeplan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeplan.setObjectName("timeplan")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.timeplan)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.timeplanlabel = QtWidgets.QLabel(self.timeplan)
        self.timeplanlabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.timeplanlabel.setFont(font)
        self.timeplanlabel.setStyleSheet("font-size:25px; background:none;\n"
"color: rgba(255, 255, 255, 200);")
        self.timeplanlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeplanlabel.setObjectName("timeplanlabel")
        self.verticalLayout_7.addWidget(self.timeplanlabel)
        self.gridLayout_11.addWidget(self.timeplan, 0, 0, 1, 2)
        self.scrollframe = QtWidgets.QFrame(self.overview)
        self.scrollframe.setMinimumSize(QtCore.QSize(644, 0))
        self.scrollframe.setStyleSheet("QFrame#frame_3{background-color:rgb(0,0,0,80);}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68, 0);\n"
"    width: 8px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    \n"
"    background-color: rgba(0, 0, 0, 120);\n"
"    min-height: 30px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    \n"
"    background-color: rgb(189, 223, 246, 180);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    \n"
"    background-color: rgba(189, 223, 246, 100);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90, 0);\n"
"    height: 0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127, 0);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92, 0);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90, 0);\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127, 0);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92, 0);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    \n"
"    background-color: rgb(255, 85,0,0);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background-color:rgb(0,0,123,0);\n"
"}\n"
"")
        self.scrollframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollframe.setObjectName("scrollframe")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollframe)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setHorizontalSpacing(0)
        self.gridLayout_12.setVerticalSpacing(5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollframe)
        self.scrollArea_3.setStyleSheet("QScrollArea{background-color:rgb(0,0,0,80); border-radius:15px;}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:verticall{background-color:rgb(0,0,0,0);}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 642, 312))
        self.scrollAreaWidgetContents_3.setStyleSheet("background-color:rgb(0,0,0,0);")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_69 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_69.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_69.setSpacing(6)
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        self.scrollingframe = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.scrollingframe.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollingframe.setStyleSheet("QFrame#scrollingframe{background:none;}")
        self.scrollingframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollingframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollingframe.setObjectName("scrollingframe")
        self.verticalLayout_70 = QtWidgets.QVBoxLayout(self.scrollingframe)
        self.verticalLayout_70.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_70.setSpacing(0)
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.verticalLayout_69.addWidget(self.scrollingframe)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.addWidget(self.scrollArea_3, 0, 0, 1, 2)
        self.leggtilframe = QtWidgets.QFrame(self.scrollframe)
        self.leggtilframe.setMinimumSize(QtCore.QSize(0, 30))
        self.leggtilframe.setMaximumSize(QtCore.QSize(16777215, 30))
        self.leggtilframe.setStyleSheet("background:none;")
        self.leggtilframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leggtilframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leggtilframe.setObjectName("leggtilframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.leggtilframe)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fjern = QtWidgets.QPushButton(self.leggtilframe)
        self.fjern.setMinimumSize(QtCore.QSize(70, 25))
        self.fjern.setStyleSheet("QPushButton{\n"
"border:1px solid;\n"
"border-color: rgb(39, 39, 39);\n"
"border-radius:0px;\n"
"border-radius:10px;\n"
"background-color: rbg(0,0,0,80);\n"
"color: rgb(217, 217, 217);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0, 0, 0, 120);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(0, 0, 0, 200);\n"
"}")
        self.fjern.setObjectName("fjern")
        self.horizontalLayout.addWidget(self.fjern)
        self.fjern_2 = QtWidgets.QPushButton(self.leggtilframe)
        self.fjern_2.setMinimumSize(QtCore.QSize(70, 25))
        self.fjern_2.setStyleSheet("QPushButton{\n"
"border:1px solid;\n"
"border-color: rgb(39, 39, 39);\n"
"border-radius:0px;\n"
"border-radius:10px;\n"
"background-color: rbg(0,0,0,80);\n"
"color: rgb(217, 217, 217);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0, 0, 0, 120);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(0, 0, 0, 200);\n"
"}")
        self.fjern_2.setObjectName("fjern_2")
        self.horizontalLayout.addWidget(self.fjern_2)
        self.fjern_3 = QtWidgets.QPushButton(self.leggtilframe)
        self.fjern_3.setMinimumSize(QtCore.QSize(70, 25))
        self.fjern_3.setStyleSheet("QPushButton{\n"
"border:1px solid;\n"
"border-color: rgb(39, 39, 39);\n"
"border-radius:0px;\n"
"border-radius:10px;\n"
"background-color: rbg(0,0,0,80);\n"
"color: rgb(217, 217, 217);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0, 0, 0, 120);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(0, 0, 0, 200);\n"
"}")
        self.fjern_3.setObjectName("fjern_3")
        self.horizontalLayout.addWidget(self.fjern_3)
        self.leggtil = QtWidgets.QPushButton(self.leggtilframe)
        self.leggtil.setMinimumSize(QtCore.QSize(70, 25))
        self.leggtil.setStyleSheet("QPushButton{\n"
"border:1px solid;\n"
"border-color: rgb(39, 39, 39);\n"
"border-radius:0px;\n"
"border-radius:10px;\n"
"background-color: rbg(0,0,0,80);\n"
"color: rgb(217, 217, 217);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0, 0, 0, 120);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(0, 0, 0, 200);\n"
"}")
        self.leggtil.setObjectName("leggtil")
        self.horizontalLayout.addWidget(self.leggtil)
        self.gridLayout_12.addWidget(self.leggtilframe, 1, 0, 1, 2)
        self.gridLayout_11.addWidget(self.scrollframe, 1, 0, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.overview)
        self.frame_35.setMinimumSize(QtCore.QSize(644, 0))
        self.frame_35.setStyleSheet("background-color:rgb(0,0,0,0); corner-radius:15px;")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_72 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_72.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_72.setSpacing(4)
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setStyleSheet("border-radius:15px;\n"
"background-color:rgb(0,0,0,80); \n"
"")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_72.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_35)
        self.frame_37.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_37.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_37.setStyleSheet("background:none;")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_72.addWidget(self.frame_37)
        self.gridLayout_11.addWidget(self.frame_35, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centrawidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeplanlabel.setText(_translate("MainWindow", "Timeplan"))
        self.fjern.setToolTip(_translate("MainWindow", "Fjern markert(e) pasienter fra timeplanen."))
        self.fjern.setText(_translate("MainWindow", "Fjern pasient:"))
        self.fjern_2.setToolTip(_translate("MainWindow", "Sett pasient inn midt i planen. Fører pasienten frem i køen og forskyver behandlingstidspunktene til pasientene bak i køen."))
        self.fjern_2.setText(_translate("MainWindow", "Sett inn pasient:"))
        self.fjern_3.setToolTip(_translate("MainWindow", "Bytt timeplanene til to pasienter. Merk: kun to pasienter kan byttes om gangen."))
        self.fjern_3.setText(_translate("MainWindow", "Bytt pasienter:"))
        self.leggtil.setToolTip(_translate("MainWindow", "Legger til en pasient bakerst i timeplanen."))
        self.leggtil.setText(_translate("MainWindow", "Legg til pasient:"))
import Bakgrunnsbilde_rc
